# Generated by Django 2.2 on 2019-06-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount_details',
            old_name='date',
            new_name='amt_date',
        ),
    ]
