# Generated by Django 2.2 on 2019-06-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccounts', '0002_auto_20190607_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount_details',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
