# Generated by Django 2.2 on 2019-06-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccounts', '0004_auto_20190609_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount_details',
            name='remark',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
