# Generated by Django 2.2 on 2019-06-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccounts', '0007_auto_20190614_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='fee',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='amount',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='commission',
            field=models.FloatField(default='0'),
        ),
    ]
