# Generated by Django 2.2 on 2019-07-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_date', models.DateTimeField(max_length=50)),
                ('user_id', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('price', models.FloatField(default='0')),
                ('flag', models.CharField(max_length=250)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
