# Generated by Django 2.2 on 2019-07-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsgsale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='flag',
            field=models.IntegerField(default='0'),
        ),
    ]
