# Generated by Django 2.2 on 2019-07-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsgsale', '0003_auto_20190717_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='user_id',
            field=models.IntegerField(default='0'),
        ),
    ]
