# Generated by Django 2.2 on 2019-07-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsgsale', '0004_auto_20190717_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
