# Generated by Django 2.2 on 2019-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsgsale', '0006_auto_20190718_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='purch_first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product_details',
            name='purch_last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product_details',
            name='purch_userid',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='product_details',
            name='purch_username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
