# Generated by Django 2.2 on 2019-07-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpsgsale', '0007_auto_20190721_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='purch_date',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
